version: '2'

services:
  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "12201:12201/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: kibana/
    ports:
      - "5601:5601"